var language = {
    cy: {
        letters: [
            ["Аа",'a'],["Бб",'b'],["Вв",'v'],
            ["Гг",'g'],["Дд",'d'],["Ее",'e'],
            ["Ёё",'yo'],["Жж",'zh'],["Зз",'z'],
            ["Ии",'i'],["Йй",'y'],["Кк",'k'],
            ["Лл",'l'],["Мм",'m'],["Нн",'n'],
            ["Оо",'o'],["Пп",'p'],["Рр",'r'],
            ["Сс",'s'],["Тт",'t'],["Уу",'u'],
            ["Фф",'f'],["Хх",'x'],["Цц",'ts'],
            ["Чч",'ch'],["Шш",'sh'],["Щщ",'sch'],
            ["Ъъ",'npl'],["Ыы",'ih'],["Ьь",'pl'],
            ["Ээ",'e'],["Юю",'yu'],["Яя",'ya']
        ],
        extraletters: [
          ['Ґґ','g'],['Ђђ','j'],['Ѓѓ','j'],
          ['Єє','ye'],['З́﻿з́','zh'],['Ѕѕ','dz'],
          ['Іі','i'],['Її','yi'],['Јј','y'],
          ['Љљ','ly'],['Њњ','gn'],['С́﻿с́','sh'],
          ['Ћћ','ch'],['Ќќ','ch'],['Ўў','w'],
          ['Џџ','j'],['Њњ','gn'],['Ӏӏ','_'],
          ['Әә','ah'],['Ғғ','r'],['Ҙҙ','dh'],
          ['Ҫҫ','th'],['Ҡҡ','q'],['Җҗ','j'],
          ['Ққ','q'],['Ңң','ng'],['Ҥҥ','ng'],
          ['Өө','ur'],['Үү','yy'],['Ұұ','u'],
          ['Һһ','h'],['Ҳҳ','h'],['Ӑӑ','uh']
        ],
        direction: 'ltr',
        name: 'Cyrillic Script',
        namealt: 'Кириллица',
        id: 'cy',
        type: 'alphabet',
        web: 'https://en.wikipedia.org/wiki/Cyrillic_script',
        webalt: 'https://ru.wikipedia.org/wiki/%D0%9A%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%D0%B8%D1%86%D0%B0',
        cases: ["Uppercase","Lowercase"],
        locations: ["Eastern Europe","Southeastern Europe","Central Asia"],
        languages: ["Russian", "Ukrainian", "Kazakh","Serbian","Bulgarian"]
    },
    gr: {
        letters: [
          ["Αα",'a','άλφα','alpha'],["Ββ",'v','βήτα','beta'],["Γγ",'gy','γάμμα','gamma'],
          ["Δδ",'dh','δέλτα','delta'],["Εε",'e','έψιλον','epsilon'],["Ζζ",'z','ζήτα','zeta'],
          ["Ηη",'i','ήτα','eta'],["Θθ",'th','θήτα','theta'],["Ιι",'i','ιώτα','iota'],
          ["Κκ",'k','κάππα','kappa'],["Λλ",'l','λάμδα','lambda'],["Μμ",'m','μυ','mu'],
          ["Νν",'n','νυ','nu'],["Ξξ",'ks','ξι','xi'],["Οο",'o','όμικρον','omicron'],
          ["Ππ",'p','πι','pi'],["Ρρ",'r','ρώ','rho'],["Σσς",'s','σίγμα','sigma'],
          ["Ττ",'t','ταυ','tau'],["Υυ",'y','ύψιλον','upsilon'],["Φφ",'f','φι','phi'],
          ["Χχ",'x','χι','chi'],["Ψψ",'ps','ψι','psi'],["Ωω",'o','ωμέγα','omega']
        ],
        direction: 'ltr',
        name: 'Greek Alphabet',
        namealt: 'Ελληνικό Αλφάβητο',
        id: 'gr',
        type: 'alphabet',
        web: 'https://en.wikipedia.org/wiki/Greek_alphabet',
        webalt: 'https://el.wikipedia.org/wiki/%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CF%8C_%CE%B1%CE%BB%CF%86%CE%AC%CE%B2%CE%B7%CF%84%CE%BF',
        cases: ["Uppercase","Lowercase","Final"],
        locations: ["Greece","Cyprus"],
        languages: ["Greek"]
      },
      he: {
        letters: [
          ['א‬','_','אָלֶף‬','alef'],['בּ‬','b','בֵּית‬','bet'],['ב‬','v','בֵית‬','vet'],
          ['ג‬','g','גִימֵל‬','gimel'],['ד‬','d','דָלֶת‬','dalet'],['ה‬','h','הֵא‬','He'],
          ['ו‬','v','וָו‬','vav'],['וֹ','o','חוֹלָם‬ מָלֵא','holam male'],['וּ','u','שׁוּרוּק','shuruk'],
          ['ז‬','z','זַיִן‬','zayin'],['ח‬','x','חֵית‬','het'],
          ['ט‬','t','טֵית‬','tet'],['י‬','y','יוֹד‬','yod'],['כּ‬','k','כַּף‬','kaf'],
          ['כך','x','כַף‬','khaf'],['ל','l','לָמֶד‬','lamed'],['מם','m','מֵם‬','mem'],
          ['נן','n','נוּן‬','nun'],['ס','s','סָמֶך‬','samekh'],['ע','_','עַיִן‬','ayin'],
          ['פּ','p','פֵּא','pe'],['פף','f','פֵא','fe'],['צץ','ts','צַדִי','tsadi'],
          ['ק','k','קוֹף‬','qof'],['ר','r','רֵישׁ‬','resh'],['שׁ','sh','שִׁין‬','shin'],
          ['שׂ','s','שִׂין‬','sin'],['ת','t','תָו','tav']
        ],
        vowels: [
          [' ַ','a'],
          [' ָ','a'],[' ֵ','e'],[' ֶ','e'],
          [' ֹ','o'],[' ֻ','u'],[' ִ','i'],
          [' ְ','silent']
        ],
        direction: 'rtl',
        name: 'Hebrew Alphabet',
        namealt: 'אלפבית עברי',
        id: 'he',
        type: 'abjad',
        web: 'https://en.wikipedia.org/wiki/Hebrew_alphabet',
        webalt: 'https://he.wikipedia.org/wiki/%D7%90%D7%9C%D7%A4%D7%91%D7%99%D7%AA_%D7%A2%D7%91%D7%A8%D7%99',
        cases: ["","Final"],
        locations: ["Israel"],
        languages: ["Hebrew","Yiddish"]
      },
      am: {
        letters: [
          ['Աա','a'],['Բբ','b'],['Գգ','g'],
          ['Դդ','d'],['Եե','e'],['Զզ','z'],
          ['Էէ','e'],['Ըը','uh'],['Թթ','t asp'],
          ['Ժժ','zh'],['Իի','i'],['Լլ','l'],
          ['Խխ','x'],['Ծծ','ts'],['Կկ','k'],
          ['Հհ','h'],['Ձձ','dz'],['Ղղ','r'],
          ['Ճճ','ch'],['Մմ','m'],['Յյ','y'],
          ['Նն','n'],['Շշ','sh'],['Ոո','aa'],
          ['Չչ','ch asp'],['Պպ','p'],['Ջջ','j'],
          ['Ռռ','r'],['Սս','s'],['Վվ','v'],
          ['Տտ','t'],['Րր','r'],['Ցց','ts asp'],
          ['Ււ','v'],['Փփ','p asp'],['Քք','k asp'],
          ['և','ev'],['Օօ','o'],['Ֆֆ','f']
        ],
        direction: 'ltr',
        name: 'Armenian Alphabet',
        namealt: 'Հայերենի այբուբեն',
        id: 'am',
        type: 'alphabet',
        web: 'https://en.wikipedia.org/wiki/Armenian_alphabet',
        webalt: 'https://hy.wikipedia.org/wiki/%D5%80%D5%A1%D5%B5%D5%A5%D6%80%D5%A5%D5%B6%D5%AB_%D5%A1%D5%B5%D5%A2%D5%B8%D6%82%D5%A2%D5%A5%D5%B6',
        cases: ["Uppercase","Lowercase"],
        locations: ["Armenia"],
        languages: ["Armenian"]
      },
      ge: {
        letters: [
          ['ა','a'],['ბ','b'],['გ','g'],
          ['დ','d'],['ე','e'],['ვ','v'],
          ['ზ','z'],['თ','t'],['ი','i'],
          ['კ','k'],['ლ','l'],['მ','m'],
          ['ნ','n'],['ო','aa'],['პ','p'],
          ['ჟ','zh'],['რ','r'],['ს','s'],
          ['ტ','t'],['უ','u'],['ფ','p'],
          ['ქ','k'],['ღ','gy'],['ყ','q'],
          ['შ','sh'],['ჩ','ch'],['ც','ts'],
          ['ძ','dz'],['წ','ts'],['ჭ','ch'],
          ['ხ','x'],['ჯ','j'],['ჰ','h']
        ],
        direction: 'ltr',
        name: 'Georgian Alphabet',
        namealt: 'ქართული დამწერლობა',
        id: 'ge',
        type: 'alphabet',
        web: 'https://en.wikipedia.org/wiki/Georgian_scripts',
        webalt: 'https://ka.wikipedia.org/wiki/%E1%83%A5%E1%83%90%E1%83%A0%E1%83%97%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%93%E1%83%90%E1%83%9B%E1%83%AC%E1%83%94%E1%83%A0%E1%83%9A%E1%83%9D%E1%83%91%E1%83%90',
        cases: [""],
        locations: ["Georgia (country)"],
        languages: ["Georgian","Mingrelian"]
      },
      ar: {
        letters: [
          ['ـا ا','a'],['ـب	ـبـ	بـ	ب','b'],['ـت	ـتـ	تـ	ت','t'],
          ['ـث ـثـ ثـ ث','th'],['ـج	ـجـ	جـ	ج','j'],['ـح	ـحـ	حـ	ح','hh'],
          ['خ	ـخـ	خـ	خ','x'],['ـد	د','d'],['ـذ	ذ','dh'],
          ['ـر	ر','r'],['ـز	ز','z'],['ـس	ـسـ	سـ	س','s'],
          ['ش	ـشـ	شـ	ش','sh'],['ـص	ـصـ	صـ	ص','s phar'],['ـض	ـضـ	ضـ	ض','d phar'],
          ['ـط	ـطـ	طـ	ط','t phar'],['ـظ	ـظـ	ظـ	ظ','dh phar'],['ـع	ـعـ	عـ	ع','_'],
          ['ـغ	ـغـ	غـ	غ','gy'],['ـف ـفـ فـ ف','f'],['ـق	ـقـ	قـ	ق','q'],
          ['ـك	ـكـ	كـ	ك','k'],['ـل	ـلـ	لـ	ل','l'],['ـم	ـمـ	مـ	م','m'],
          ['ـن	ـنـ	نـ	ن','n'],['ـه	ـهـ	هـ	ه','h'],['ـو	و','w'],
          ['ـي	ـيـ	يـ	ي','y']
        ],
        vowels: [
          [' َ','uh'],[' ِ','ih'],[' ُ','uu'],
          [' ٰ','a'],[' ٓ','a'],[' ْ','silent']
        ],
        numerals: [
          ['0','٠'],['1','١'],['2','٢'],
          ['3','٣'],['4','٤'],['5','٥'],
          ['6','٦'],['7','٧'],['8','٨'],
          ['9','٩']
        ],
        direction: 'rtl',
        name: 'Arabic Alphabet',
        namealt: 'أبجدية عربية',
        id: 'ar',
        type: 'abjad',
        web: 'https://en.wikipedia.org/wiki/Arabic_alphabet',
        webalt: 'https://ar.wikipedia.org/wiki/%D8%A3%D8%A8%D8%AC%D8%AF%D9%8A%D8%A9_%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9',
        cases: ["Uppercase","Lowercase","Final"],
        locations: ["Middle East","North Africa","Central Asia","Sahel","East Africa","Southeast Asia","South Asia"],
        languages: ["Arabic","Persian","Urdu","Pashto","Uyghur"]
      },
      tf: {
        letters: [
          ['ⴰ','ah'],['ⴱ','b'],['ⴳ','g'],
          ['ⴷ','d'],['ⴹ','d phar'],['ⴻ','uh'],
          ['ⴼ','f'],['ⴽ','k'],['ⵀ','h'],
          ['ⵃ','hh'],['ⵄ','_'],['ⵅ','x'],
          ['ⵇ','q'],['ⵉ','i'],['ⵊ','zh'],
          ['ⵍ','l'],['ⵎ','m'],['ⵏ','n'],
          ['ⵓ','u'],['ⵔ','r'],['ⵕ','r phar'],
          ['ⵖ','gy'],['ⵙ','s'],['ⵚ','s phar'],
          ['ⵛ','sh'],['ⵜ','t'],['ⵟ','t phar'],
          ['ⵡ','w'],['ⵢ','y'],['ⵣ','z'],
          ['ⵥ','z phar']
        ],
        direction: 'ltr',
        name: 'Tifinagh Alphabet',
        namealt: 'ⵜⵉⴼⵉⵏⴰⵖ',
        id: 'tf',
        type: 'alphabet',
        web: 'https://en.wikipedia.org/wiki/Tifinagh',
        webalt: 'https://en.wikipedia.org/wiki/Tifinagh',
        cases: [""],
        locations: ["North Africa"],
        languages: ["Berber"]
      },
      lt: {
        letters: [
          ['ᨀ','k'],['ᨁ','g'],['ᨂ','ng'],
          ['ᨃ','ngk'],['ᨄ','p'],['ᨅ','b'],
          ['ᨆ','m'],['ᨇ','mp'],['ᨈ','t'],
          ['ᨉ','d'],['ᨊ','n'],['ᨋ','nr'],
          ['ᨌ','c'],['ᨍ','gj'],['ᨎ','gn'],
          ['ᨏ','gnc'],['ᨐ','y'],['ᨑ','r'],
          ['ᨒ','l'],['ᨓ','w'],['ᨔ','s'],
          ['ᨕ','a'],['ᨖ','h']
        ],
        vowels: [
          ['⠀','a'],['◌ᨗ','i'],['◌ᨘ','u'],
          ['ᨙ◌','e'],['◌ᨛ','uh'],['◌ᨚ','o']
        ],
        direction: 'ltr',
        name: 'Lontara Script',
        namealt: 'ᨒᨚᨈᨑ',
        id: 'lt',
        type: 'abugida',
        web: 'https://en.wikipedia.org/wiki/Lontara_script',
        webalt: 'https://bug.wikipedia.org/wiki/%E1%A8%95%E1%A8%98%E1%A8%91%E1%A8%98%E1%A8%84%E1%A8%98_%E1%A8%94%E1%A8%98%E1%A8%92%E1%A8%84_%E1%A8%95%E1%A8%9B%E1%A8%84',
        cases: [""],
        locations: ["Sulawesi"],
        languages: ["Buginese","Makassarese","Mandar"]
      },
      th: {
        letters: [
          ['ހ‎','h'],['ށ‎','sh'],['ނ‎','n'],
          ['ރ‎','r'],['ބ‎','b'],['ޅ‎','lh'],
          ['ކ‎','k'],['އ','silent'],['ވ‎','v'],
          ['މ‎','m'],['ފ‎','f'],['ދ‎','d'],
          ['ތ‎','t'],['ލ‎','l'],['ގ‎','g'],
          ['ޏ‎','gn'],['ސ‎','s'],['ޑ‎','dd'],
          ['ޒ‎','z'],['ޓ‎','tt'],['ޔ‎','y'],
          ['ޕ‎','p'],['ޖ‎','j'],['ޗ‎','ch']
        ],
        vowels: [
          ['ަ','a'],['ާ','a long'],['ި','i'],
          ['ީ','i long'],['ު','u'],['ޫ','u long'],
          ['ެ','e'],['ޭ','e long'],['ޮ','o'],
          ['ޯ','o long'],['ް','silent'],['ޱ','nn']
        ],
        direction: 'rtl',
        name: 'Thaana',
        namealt: 'ތާނަ‎',
        id: 'th',
        type: 'abugida',
        web: 'https://en.wikipedia.org/wiki/Thaana',
        webalt: 'https://dv.wikipedia.org/wiki/%DE%8C%DE%A7%DE%82%DE%A6_%DE%87%DE%A6%DE%8D%DE%A8%DE%8A%DE%AA%DE%84%DE%A7%DE%8E%DE%AC_%DE%8C%DE%A6%DE%83%DE%AA%DE%8C%DE%A9%DE%84%DE%AA',
        cases: [""],
        locations: ["Maldives"],
        languages: ["Maldivian"]
      },
      ch: {
        vowels: ['a','e','i','o','u','uh'],
        syllables: [
          ['g','Ꭶ,Ꭸ,Ꭹ,Ꭺ,Ꭻ,Ꭼ'],
          ['h','Ꭽ,Ꭾ,Ꭿ,Ꮀ,Ꮁ,Ꮂ'],
          ['l','Ꮃ,Ꮄ,Ꮅ,Ꮆ,Ꮇ,Ꮈ'],
          ['m','Ꮉ,Ꮊ,Ꮋ,Ꮌ,Ꮍ, '],
          ['n','Ꮎ,Ꮑ,Ꮒ,Ꮓ,Ꮔ,Ꮕ'],
          ['kw','Ꮖ,Ꮗ,Ꮘ,Ꮙ,Ꮚ,Ꮛ'],
          ['s','Ꮜ,Ꮞ,Ꮟ,Ꮠ,Ꮡ,Ꮢ'],
          ['d','Ꮣ,Ꮥ,Ꮧ,Ꮩ,Ꮪ,Ꮫ'],
          ['t','Ꮤ,Ꮦ,Ꮨ, , , '],
          ['tl','Ꮭ,Ꮮ,Ꮯ,Ꮰ,Ꮱ,Ꮲ'],
          ['ts','Ꮳ,Ꮴ,Ꮵ,Ꮶ,Ꮷ,Ꮸ'],
          ['w','Ꮹ,Ꮺ,Ꮻ,Ꮼ,Ꮽ,Ꮾ'],
          ['y','Ꮿ,Ᏸ,Ᏹ,Ᏺ,Ᏻ,Ᏼ'],
        ],
        othersyllables: [
          ['Ꭷ','k+a'],['Ꮏ','hn+a'],['Ꮐ','n+a long'],
          ['Ꮬ','dl+a']
        ],
        letters: [
          ['Ꮝ','s'],['Ꭰ','a'],['Ꭱ','e'],
          ['Ꭲ','i'],['Ꭳ','o'],['Ꭴ','u'],
          ['Ꭵ','uh']
        ],
        direction: 'ltr',
        name: 'Cherokee Syllabary',
        namealt: 'ᏣᎳᎩ',
        id: 'ch',
        type: 'syllabary',
        web: 'https://en.wikipedia.org/wiki/Cherokee_syllabary',
        webalt: 'https://chr.wikipedia.org/wiki/%E1%8F%A3%E1%8E%B3%E1%8E%A9_%E1%8E%A7%E1%8F%AC%E1%8F%82%E1%8E%AF%E1%8F%8D%E1%8F%97',
        cases: [""],
        locations: ["Cherokee Nation"],
        languages: ["Cherokee"]
      },
      hi: {
        vowels: ['a','i','u','e','o','ya','yu','yo'],
        syllables: [
          ['k','か,き,く,け,こ'],
          ['s','さ, ,す,せ,そ'],
          ['t','た, , ,て,と'],
          ['n','な,に,ぬ,ね,の'],
          ['h','は,ひ, ,へ,ほ'],
          ['m','ま,み,む,め,も'],
          ['y','や, ,ゆ, ,よ'],
          ['r','ら,り,る,れ,ろ'],
          ['w','わ, , , ,を'],
          ['g','が,ぎ,ぐ,げ,ご'],
          ['z','ざ, ,ず,ぜ,ぞ'],
          ['d','だ, , ,で,ど'],
          ['b','ば,び,ぶ,べ,ぼ'],
          ['p','ぱ,ぴ,ぷ,ぺ,ぽ']
        ],
        othersyllables: [
          ['つ','ts+u'],['ふ','f+u'],['づ','z+u'],
          ['づ','dz+u'],['ち','ch+i'],['し','sh+i'],
          ['じ','j+i'],['ぢ','j+i']      
        ],
        letters: [
          ['ん','n'],['あ','a'],['い','i'],
          ['う','u'],['え','e'],['お','o'],
          ['ゃ','a'],['ゅ','u'],['ょ','o']
        ],
        direction: 'ltr',
        name: 'Hiragana',
        namealt: 'ひらがな',
        id: 'hi',
        type: 'syllabary',
        web: 'https://en.wikipedia.org/wiki/Hiragana',
        webalt: 'https://ja.wikipedia.org/wiki/%E5%B9%B3%E4%BB%AE%E5%90%8D',
        cases: [""],
        locations: ["Japan"],
        languages: ["Japanese"]
      },
      kt: {
        vowels: ['a','i','u','e','o','ya','yu','yo'],
        syllables: [
          ['k','カ,キ,ク,ケ,コ'],
          ['s','サ, ,ス,セ,ソ'],
          ['t','タ, , ,テ,ト'],
          ['n','ナ,ニ,ヌ,ネ,ノ'],
          ['h','ハ,ヒ, ,ヘ,ホ'],
          ['m','マ,ミ,ム,メ,モ'],
          ['y','ヤ, ,ユ, ,ヨ'],
          ['r','ラ,リ,ル,レ,ロ'],
          ['w','ワ,ヰ, ,ヱ,ヲ'],
          ['g','ガ,ギ,グ,ゲ,ゴ'],
          ['z','ザ, ,ズ,ゼ,ゾ'],
          ['d','ダ, , ,デ,ド'],
          ['b','バ,ビ,ブ,ベ,ボ'],
          ['p','パ,ピ,プ,ペ,ポ']
        ],
        othersyllables: [
          ['ツ','ts+u'],['フ','f+u'],['ズ','z+u'],
          ['ヅ','z+u'],['シ','sh+i'],['チ','ch+i'],
          ['ぢ','j+i'],['ヂ','j+i']       
        ],
        letters: [
          ['ン','n'],['ア','a'],['イ','i'],
          ['ウ','u'],['エ','e'],['オ','o'],
          ['ャ','a'],['ュ','u'],['ョ','o']
        ],
        direction: 'ltr',
        name: 'Katakana',
        namealt: 'カタカナ',
        id: 'kt',
        type: 'syllabary',
        web: 'https://en.wikipedia.org/wiki/Katakana',
        webalt: 'https://ja.wikipedia.org/wiki/%E7%89%87%E4%BB%AE%E5%90%8D',
        cases: [""],
        locations: ["Japan"],
        languages: ["Japanese"]
      },
      gz: {
        vowels: ['uh','u','i','a','e','yy','o','wa','yuh'],
        syllables: [
          ['h','ሀ,ሁ,ሂ,ሃ,ሄ,ህ,ሆ'],
          ['l','ለ,ሉ,ሊ,ላ,ሌ,ል,ሎ,ሏ'],
          ['h','ሐ,ሑ,ሒ,ሓ,ሔ,ሕ,ሖ,ሗ'],
          ['m','መ,ሙ,ሚ,ማ,ሜ,ም,ሞ,ሟ,ፙ'],
          ['s','ሠ,ሡ,ሢ,ሣ,ሤ,ሥ,ሦ,ሧ'],
          ['r','ረ,ሩ,ሪ,ራ,ሬ,ር,ሮ,ሯ,ፘ'],
          ['s','ሰ,ሱ,ሲ,ሳ,ሴ,ስ,ሶ,ሷ'],
          ['k ejc','ቀ,ቁ,ቂ,ቃ,ቄ,ቅ,ቆ,ቋ'],
          ['b','በ,ቡ,ቢ,ባ,ቤ,ብ,ቦ,ቧ'],
          ['t','ተ,ቱ,ቲ,ታ,ቴ,ት,ቶ,ቷ'],
          ['h','ኀ,ኁ,ኂ,ኃ,ኄ,ኅ,ኆ,ኋ'],
          ['n','ነ,ኑ,ኒ,ና,ኔ,ን,ኖ,ኗ'],
          ['_','አ,ኡ,ኢ,ኣ,ኤ,እ,ኦ,ኧ'],
          ['k','ከ,ኩ,ኪ,ካ,ኬ,ክ,ኮ,ኳ'],
          ['w','ወ,ዉ,ዊ,ዋ,ዌ,ው,ዎ'],
          ['_','ዐ,ዑ,ዒ,ዓ,ዔ,ዕ,ዖ'],
          ['z','ዘ,ዙ,ዚ,ዛ,ዜ,ዝ,ዞ,ዟ'],
          ['y','የ,ዩ,ዪ,ያ,ዬ,ይ,ዮ'],
          ['d','ደ,ዱ,ዲ,ዳ,ዴ,ድ,ዶ,ዷ'],
          ['t ejc','ጠ,ጡ,ጢ,ጣ,ጤ,ጥ,ጦ,ጧ'],
          ['p ejc','ጰ,ጱ,ጲ,ጳ,ጴ,ጵ,ጶ,ጷ'],
          ['ts ejc','ጸ,ጹ,ጺ,ጻ,ጼ,ጽ,ጾ,ጿ'],
          ['ts ejc','ፀ,ፁ,ፂ,ፃ,ፄ,ፅ,ፆ'],
          ['f','ፈ,ፉ,ፊ,ፋ,ፌ,ፍ,ፎ,ፏ,ፚ'],
          ['p','ፐ,ፑ,ፒ,ፓ,ፔ,ፕ,ፖ,ፗ'],
          ['k ejc lab','ቈ, ,ቊ,ቋ,ቌ,ቍ'],
          ['h lab','ኈ, ,ኊ,ኋ,ኌ,ኍ'],
          ['k lab','ኰ, ,ኲ,ኳ,ኴ,ኵ'],
          ['g lab','ጐ, ,ጒ,ጓ,ጔ,ጕ'],
          ['sh','ሸ,ሹ,ሺ,ሻ,ሼ,ሽ,ሾ,ሿ'],
          ['v','ቨ,ቩ,ቪ,ቫ,ቬ,ቭ,ቮ,ቯ'],
          ['ch','ቸ,ቹ,ቺ,ቻ,ቼ,ች,ቾ,ቿ'],
          ['gn','ኘ,ኙ,ኚ,ኛ,ኜ,ኝ,ኞ,ኟ'],
          ['h','ኸ,ኹ,ኺ,ኻ,ኼ,ኽ,ኾ'],
          ['zh','ዠ,ዡ,ዢ,ዣ,ዤ,ዥ,ዦ,ዧ'],
          ['j','ጀ,ጁ,ጂ,ጃ,ጄ,ጅ,ጆ,ጇ'],
          ['ch ejc','ጨ,ጩ,ጪ,ጫ,ጬ,ጭ,ጮ,ጯ'],
        ],
        othersyllables: [],
        letters: [],
        direction: 'ltr',
        name: "Ge'ez Script",
        namealt: 'ግዕዝ',
        id: 'gz',
        type: 'syllabary',
        web: 'https://en.wikipedia.org/wiki/Ge%27ez_script',
        webalt: 'https://am.wikipedia.org/wiki/%E1%8C%8D%E1%8B%95%E1%8B%9D',
        cases: [""],
        locations: ["Ethiopia","Eritrea"],
        languages: ["Amharic","Tigrinya","Tigre","Bilen"]
      },
      nk: {
        letters: [
            ["ߊ‎",'ah'],["ߋ‎",'ey'],["ߌ‎",'i'],
            ["ߍ‎",'e'],["ߎ‎",'u'],["ߏ‎",'o'],
            ["ߐ‎",'aa'],["ߓ‎",'b'],["ߔ‎",'p'],
            ["ߕ‎",'t'],["ߖ‎",'j'],["ߗ‎",'ch'],
            ["ߘ‎",'d'],["ߙ‎",'r'],["ߚ‎",'r'],
            ["ߛ‎",'s'],["ߜ‎",'gb'],["ߝ‎",'f'],
            ["ߞ‎",'k'],["ߟ‎",'l'],["ߡ‎",'m'],
            ["ߢ‎",'gn'],["ߣ‎",'n'],["ߤ‎",'h'],
            ["ߥ‎",'w'],["ߦ‎",'y'],["ߒ‎",'n'],
            ['߫‎','nk_hs'],[' ߬‎','nk_ls'],[' ߭‎','nk_rs'],
            [' ߯‎','nk_hl'],[' ߰‎','nk_ll'],[' ߱','nk_rl'],
            [' ߮','nk_fl']
        ],
        numerals: [
          ['0','߀‎'],['1','߁'],['2','߂‎'],
          ['3','߃‎'],['4','߄‎'],['5','߅‎'],
          ['6','߆'],['7','߇‎'],['8','߈‎'],
          ['9','߉‎']
        ],
        direction: 'rtl',
        name: "N'Ko Alphabet",
        namealt: 'ߒߞߏ‎',
        id: 'nk',
        type: 'alphabet',
        web: 'https://en.wikipedia.org/wiki/N%27Ko_alphabet',
        webalt: 'https://en.wikipedia.org/wiki/N%27Ko_alphabet',
        cases: [""],
        locations: ["West Africa"],
        languages: ["Mandinka","Maninka"]
    },
};
for(var u = 0; u < language["ar"]["letters"].length; u++){
  language["ar"]["letters"][u][0] = language["ar"]["letters"][u][0].replace(/\t/g, ' ');
  language["ar"]["letters"][u][0] = language["ar"]["letters"][u][0].split(" ");
  language["ar"]["letters"][u][0] = language["ar"]["letters"][u][0].reverse();
  language["ar"]["letters"][u][0] = language["ar"]["letters"][u][0].join(" ");
}
